module.exports = {
  apps: [
    {
      name: "vulcan-api",
      cwd: "/home/linuxuser/projects/vulcan",
      script: "pnpm",
      args: "api:start",
      autorestart: true,
      restart_delay: 1500,
      max_restarts: 50,
      kill_timeout: 5000,
      time: true,
      env: {
        NODE_ENV: "production",
        VULCAN_API_PORT: "8787",
        VULCAN_CORS_ORIGIN: "*",
        DATABASE_URL: "",
        REDIS_URL: "",
      },
      env_production: {
        NODE_ENV: "production",
        VULCAN_API_PORT: "8787",
        VULCAN_CORS_ORIGIN: "*",
        DATABASE_URL: "",
        REDIS_URL: "",
      },
    },
    {
      name: "vulcan-mc",
      cwd: "/home/linuxuser/projects/vulcan",
      script: "pnpm",
      args: "start",
      autorestart: true,
      restart_delay: 2000,
      max_restarts: 20,
      kill_timeout: 5000,
      time: true,
      env: {
        NODE_ENV: "production",
        PORT: "3001",
        NEXT_PUBLIC_VULCAN_WS_URL: "ws://127.0.0.1:8787/api/ws",
      },
      env_production: {
        NODE_ENV: "production",
        PORT: "3001",
        NEXT_PUBLIC_VULCAN_WS_URL: "ws://127.0.0.1:8787/api/ws",
      },
    },
    {
      name: "vulcan-adapter",
      cwd: "/home/linuxuser/projects/vulcan",
      script: "pnpm",
      args: "adapter",
      autorestart: true,
      restart_delay: 1500,
      max_restarts: 50,
      kill_timeout: 5000,
      time: true,
      env: {
        NODE_ENV: "production",
        VULCAN_INGEST_URL: "http://127.0.0.1:8787/api/adapter/ingest",
        OPENCLAW_LOG_DIR: "/tmp/openclaw",
        OPENCLAW_LOG_FILE: "",
        ADAPTER_POLL_MS: "2000",
        ADAPTER_HEARTBEAT_MS: "45000",
        ADAPTER_MAX_EVENTS_PER_MIN: "20",
        ADAPTER_MAX_BATCH: "5",
        ADAPTER_DRY_RUN: "0",
      },
      env_production: {
        NODE_ENV: "production",
        VULCAN_INGEST_URL: "http://127.0.0.1:8787/api/adapter/ingest",
        OPENCLAW_LOG_DIR: "/tmp/openclaw",
        OPENCLAW_LOG_FILE: "",
        ADAPTER_POLL_MS: "2000",
        ADAPTER_HEARTBEAT_MS: "45000",
        ADAPTER_MAX_EVENTS_PER_MIN: "20",
        ADAPTER_MAX_BATCH: "5",
        ADAPTER_DRY_RUN: "0",
      },
    },
  ],
};
